sudo: required

services:
  - docker

language:
  - ruby

before_install:
  - docker pull jekyll/jekyll:builder

script:
  - docker run --rm -v $PWD/src:/srv/jekyll -v $PWD/apk.txt:/srv/jekyll/.apk -v $PWD/build.sh:/srv/jekyll/build.sh -e S3_ID=$S3_ID -e S3_SECRET=$S3_SECRET -e JEKYLL_ENV=$JEKYLL_ENV --entrypoint /srv/jekyll/build.sh jekyll/jekyll:builder
