language: ruby
cache: bundler

gemfile=$TRAVIS_BUILD_DIR/src/Gemfile

script:
  - bundle exec jekyll build
  - find $TRAVIS_BUILD_DIR/_site/assets/ -type f -name *.png -exec convert {} -strip {} \;
  - find $TRAVIS_BUILD_DIR/_site/assets/ -type f -name *.jpg -exec convert {} -sampling-factor 4:2:0 -strip -quality 85 -interlace JPEG -colorspace RGB {} \;
  - bundle exec s3_website push
