sudo: false
language: ruby
rvm:
  - 2.6
jdk:
  - openjdk8
cache: bundler
gemfile: src/Gemfile

before_install:
  - gem install bundler

script:
  - cd src/
  - bundle exec jekyll build
  - find _site/assets/ -type f -name *.png -exec convert {} -strip {} \;
  - find _site/assets/ -type f -name *.jpg -exec convert {} -sampling-factor 4:2:0 -strip -quality 85 -interlace JPEG -colorspace RGB {} \;
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then java -cp $(bundle show s3_website)/*.jar s3.website.Push; fi'

branches:
  only:
    - master
