# Site settings
title: Grain
description: Nibbles of code, software development, and misc. tech stuff
url: http://blog.jvtrigueros.com

author:
  name     : Jose V. Trigueros
  email    : j.v.trigueros+blog@gmail.com
  url      : http://blog.jvtrigueros.com
  # facebook : http://facebook.com/
  twitter  : http://twitter.com/jvtrigueros

github: https://github.com/jvtrigueros/blog.jvtrigueros.com
disqus_shortname: grain-blog
google_analytics: UA-59713858-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

gems:
  - jekyll-paginate

markdown: redcarpet

exclude:
  - Gemfile
  - Gemfile.lock
  - s3_website.yml
