# Site settings
title: Grain
description: Thoughts of a Software Developer
url: https://blog.jvtrigueros.com

author:
  name     : Jose V. Trigueros
  email    : j.v.trigueros+blog@gmail.com
  url      : https://blog.jvtrigueros.com
  linkedin : https://www.linkedin.com/in/jvtrigueros/
  twitter  : https://twitter.com/jvtrigueros

github: https://github.com/jvtrigueros/blog.jvtrigueros.com
disqus_shortname: grain-blog
google_analytics: UA-59713858-1

paginate: 5
paginate_path: "/page/:num"
permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

sass:
  style: :compressed
  sass_dir: _sass

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
