# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

group :development do
  gem 'sass', '~> 3.4.25'
  gem 'jekyll', '~> 3.8.5'
  gem 'redcarpet', '~> 3.5.1'
  gem 's3_website', '~> 3.4.0'
end

group :jekyll_plugins do
  gem 'jekyll-compose'
  gem 'jekyll-paginate'
end
