# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

group :development do
  gem 'sass', '~> 3.4.25'
  gem 'jekyll', '~> 3.5.0'
  gem 'jekyll-paginate', '~> 1.1.0'
  gem 'redcarpet', '~> 3.4.0'
  gem 's3_website'
end

group :jekyll_plugins do
  gem 'jekyll-compose'
end
